AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Optimism ID demo template

Parameters:
  StackName:
    Description: The cloudformation stack name, MUST be lower case
    Type: String
  DomainName:
    Description: The domain name of the existing Route 53 hosted zone, should match HostedZoneId
    Type: String

Resources:
  UI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: packages/ui/template.yml
      Parameters:
        StackName: !Ref StackName
        DomainName: !Ref DomainName

Outputs:
  UIUrl:
    Description: UI public access URL
    Value: !GetAtt UI.Outputs.Url
