/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_RPC_URL: string
  readonly VITE_WALLET_CONNECT_ID: string
  readonly VITE_ISSUER_URL: string
  readonly VITE_ISSUER_DID: string
  readonly VITE_ISSUER_USER: string
  readonly VITE_ISSUER_PASSWORD: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}